function(mnx_enable_sanitizers target)
    if(NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
        return()
    endif()

    if(MSVC)
        if(MNX_ENABLE_ASAN)
            target_compile_options(${target} PRIVATE /fsanitize=address)
            target_link_options(${target} PRIVATE /fsanitize=address)
        endif()
        return()
    endif()

    set(sanitizers "")
    if(MNX_ENABLE_ASAN)
        list(APPEND sanitizers "address")
    endif()
    if(MNX_ENABLE_UBSAN)
        list(APPEND sanitizers "undefined")
    endif()

    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_flags)
        target_compile_options(${target} PRIVATE "-fsanitize=${sanitizer_flags}" -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE "-fsanitize=${sanitizer_flags}")
    endif()
endfunction()
